# Generated by Django 5.2.16 on 2026-07-22 16:57

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    TherapistProfile = apps.get_model("accounts", "TherapistProfile")
    used_slugs = set(
        TherapistProfile.objects.exclude(slug__isnull=True)
        .exclude(slug="")
        .values_list("slug", flat=True)
    )

    for profile in TherapistProfile.objects.order_by("pk"):
        if profile.slug:
            continue
        base_slug = slugify(profile.display_name) or "terapeut"
        slug = base_slug
        index = 2
        while slug in used_slugs:
            slug = f"{base_slug}-{index}"
            index += 1
        profile.slug = slug
        profile.save(update_fields=["slug"])
        used_slugs.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_therapistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='therapistprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=170, unique=True),
        ),
    ]
